// <auto-generated />
namespace ElevenNote.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedEnumSubjectType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedEnumSubjectType));
        
        string IMigrationMetadata.Id
        {
            get { return "201811261712412_addedEnumSubjectType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
